#!/bin/sh

rifle_cmd="rifle -c ${HOME}/.config/rifle.conf"

options=$($rifle_cmd -l $1)
echo "$options"
echo ""
echo "Open with: "
read selection

case "$selection" in
  "cd")
    [ -f "$1" ] && cd $(dirname "$1") && exec bash || [ -d "$1" ] && cd "$1" && exec bash
    ;;
  "echo")
    echo "$1"
    ;;
  *)
    $rifle_cmd -p "$selection" "$1" || printf "\# Command failed $selection $1"
    ;;
esac
